### ISSUE TITLE
rtree doesn't build on OS-X

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [ioos/conda-recipes#104]
Getting error:

Package: rtree-0.7.0-py27_0

source tree in: /Users/chris.barker/anaconda/conda-bld/work
+ /Users/chris.barker/anaconda/envs/_build/bin/python setup.py install

Traceback (most recent call last):

  File "setup.py", line 5, in <module>

    import rtree

  File "/Users/chris.barker/anaconda/conda-bld/work/rtree/__init__.py", line 1, in <module>

    from index import Rtree

  File "/Users/chris.barker/anaconda/conda-bld/work/rtree/index.py", line 2, in <module>

    import core

  File "/Users/chris.barker/anaconda/conda-bld/work/rtree/core.py", line 85, in <module>

    rt = ctypes.CDLL(lib_name)

  File "/Users/chris.barker/anaconda/envs/_build/lib/python2.7/ctypes/__init__.py", line 365, in __init__

    self._handle = _dlopen(self._name, mode)

OSError: dlopen(libspatialindex_c.dylib, 6): image not found

Command failed: /bin/bash -x -e /Users/chris.barker/PythonStuff/IOOS_packages/conda-recipes/rtree/build.sh

IT look slike something is wrong with teh ctypes path for finding dlls.

libspatialindex is installed, but I haven't looked yet for that dylib.

**Comment by ocefpaf** [comment]
I found two recipes on binstar for Rtree.  One is a newer version (0.8.0), but the recipe is identical to ours.

The [other](https://binstar.org/rustychris/rtree/files) is the same version, but it adds a patch that might be relevant.  I would try upgrading first, in case the patch was incorporated upstream.

**Comment by ocefpaf** [comment]
The compressed file has a recipe directory with the `bld.bat`, `build.sh`, `meta.yaml` (sometime `meta.yaml.orig` which is the real recipe! :confounded:) and the patches.

**Comment by ocefpaf** [comment]
Close in favor of #141
