### ISSUE TITLE
UDUNITS build issue on OS-X

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [ioos/conda-recipes#106]
UDUNITS calls autoreconf and fails (for me). 

I think this requires the whole autotools command set - which is not on a OS-X box be default. I can't find a version of the source that's had the configure script built.

I posted an issue on the udunits site about it.

**Comment by rsignell-usgs** [comment]
@ChrisBarker-NOAA  and @ocefpaf, we don't need to have the Mac setup that builds these be the default, right?   
I would think we (Chris) would want to install everything that the Travis Mac OS instance has installed, and if that includes the whole autotools command setup, we should do it, shouldn't we?

Although we might need these packages to build the binaries, they Anaconda folks who use them would not need them.

**Comment by ocefpaf** [comment]
> would want to install everything that the Travis Mac OS instance has installed

Yes, that is preferable.  If we get a MacOS VM from travis in the future we will maintain these packages there.  So the closest we can be to their configuration the better.

**Comment by rsignell-usgs** [comment]
Hopefully this will save @ChrisBarker-NOAA a lot of work in the build process.  Can you link here the same info you provided me about that environment?   I can't remember where that conversation was taking place.

**Comment by ocefpaf** [comment]
http://docs.travis-ci.com/user/osx-ci-environment/#Compilers-%26-Build-toolchain

**Comment by ChrisBarker-NOAA** [comment]
OK,

That does indeed include auto tools installed by Homebrew. It's a bit sad
that Ape doesn't provide a more complete build environment on it's own, but
there you go.

I still think it's a good idea for conda packages to be set up to build
with as few build requirements as possible. But that's mostly an upstream
problem.

I'll set up my machine similarly to Travis, and see how it goes.

-Chris

On Mar 4, 2015, at 4:08 AM, Filipe <notifications@github.com> wrote:

http://docs.travis-ci.com/user/osx-ci-environment/#Compilers-%26-Build-toolchain

—
Reply to this email directly or view it on GitHub
<https://github.com/ioos/conda-recipes/issues/106#issuecomment-77146964>.

**Comment by ocefpaf** [comment]
> I still think it's a good idea for conda packages to be set up to build.

Last time I requested something like that the answer was: "But which setup do you want?"  I believe the solution would be in a common build environment, like a configured virtual environment for the builds, provided/hosted by  continuum.  [binstar-build](http://docs.binstar.org/build_cli.html) is an attempt to do that, but it sucks right now.  There is nothing there, only a basic gcc, you have to create conda packages for the build tools you will use and that is way too cumbersome.  Also, they only give free access to Linux 64.

> I'll set up my machine similarly to Travis, and see how it goes.

Thanks!  That will make our job easier in the future.

**Comment by ChrisBarker-NOAA** [comment]
On Wed, Mar 4, 2015 at 8:05 AM, Filipe <notifications@github.com> wrote:

> I still think it's a good idea for conda packages to be set up to build.
>
> Last time I requested something like that the answer was: "But which setup
> do you want?"
>
Not that this is clearly defined, but the answer is: as minimal a system as
possible.

On Linux, there is so much variety, it's pretty impossible -- though at
least the full gnu toolchain is pretty easy to get.

For Windows and OS-X -- Using only stuff in Anaconda and the "system"
compiler.

Windows: That's the Visual Studio for Python2.7 (Anaconda ships with gcc,
but it's never worked for me out of the box, and continuum themselves use
the MS compiler. That it doesn't get you fortran... ( and of course, a lot
of open source pacakges don't have easy to use build scripts for Windows...)

For OS-X -- Apple's compiler as delivered.

So ideally a conda package doesn't require autotools to build, but that may
not be practical, in which case it would be nice to have an Anaconda
package for that.

It turns out that gcc that continuum uses is available in Aaron Meurer's
channel on binstar -- they may add tht to the official Anaconda channels,
which would be a good step in the right direction.


> I believe the solution would be in a common build environment, like a
> configured
>
virtual environment for the builds, provided/hosted by continuum.
>
Sure -- though providing it all in Anaconda would get us to pretty much the
same place!

> binstar-build <http://docs.binstar.org/build_cli.html> is an attempt to
> do that, but it sucks right now. There is nothing there, only a basic gcc,
> you have to create conda packages for the build tools you will use and that
> is way too cumbersome.
>
right -- but if there were already the conda c=pacakges for the build tools
we'd be in good shape.

> Also, they only give free access to Linux 64.
>
well, given Apple's licensing -- I can't expect people to provide that for
free :-(

>  I'll set up my machine similarly to Travis, and see how it goes.
>
> Thanks! That will make our job easier in the future.
>
yup -- the way to go for now anyway -- though I think we're really close to
using Anaconda out of the box.

I'm taking a look at the brew autoconf formula -- maybe it's an easy build?

-CHB


-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I am closing this since we got udunits2 on Mac using #107 in a local build.
