### ISSUE TITLE
Problems building RasterIO on RHEL6

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/conda-recipes#121]
I'm having problems building RasterIO on RHEL6:
https://gist.github.com/rsignell-usgs/79559b34d904576a8126
which I will pursue with Continuum. 

But in the meantime, let's remove it from the ioos conda-recipes

**Comment by ocefpaf** [comment]
:+1:

**Comment by pelson** [comment]
@rsignell-usgs - is it not simply that you don't have GEOS as a runtime dependency?

**Comment by pelson** [comment]
(Looks like that should be on the GDAL package?)

**Comment by rsignell-usgs** [comment]
@pelson the problem turned out to be that I had `LD_LIBRARY_PATH=/home/testbed/anaconda/lib/` and when I removed that, the build was fine.   Sheesh.
