### ISSUE TITLE
iris pp_packing format does not work

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#131]
We are following SciTools/conda-recipes-scitools closely and packaging both `libmo_unpack` and `iris` using slightly modified versions of the original recipes.  However, we [cannot import](https://github.com/ioos/conda-recipes/blob/master/iris/meta.yaml#L40-41) `iris.fileformats.pp_packing`. 

@pelson: Any advice?  You can see the error in PR #130.

**Comment by pelson** [comment]
https://github.com/SciTools/conda-recipes-scitools/blob/master/iris/build.sh#L16

vs

https://github.com/ioos/conda-recipes/blob/master/iris/build.sh

**Comment by pelson** [comment]
You need to explicitly tell setup.py to use unpacking.

**Comment by ocefpaf** [comment]
Argh!!! I missed that.  Thanks @pelson.

**Comment by ocefpaf** [comment]
PR #130 fixes this.
