### ISSUE TITLE
Deprecate cov-core

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#152]
@rsignell-usgs I recommend removing [cov-core](https://github.com/schlamar/cov-core) from the repository.  The last binary will remain in the binstart channel though.  The reasons are:

- cov-core became a legacy code of [py-cov](https://github.com/schlamar/pytest-cov) and,
- it is used only by `pytools`, which was also discontinued.

**Comment by rsignell-usgs** [comment]
That's fine with me.  @kwilcox, you okay with this?

**Comment by rsignell-usgs** [comment]
@ocefpaf, so pytools replacement pyaxiom doesn't use it?

**Comment by ocefpaf** [comment]
Nope: https://github.com/axiom-data-science/pyaxiom/blob/master/requirements.txt
