### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#17]
I am trying to re-build and `rdflib` locally, but `sparqlwrapper` depends on `rdflib` that depends on `sparqlwrapper`. @rsignell-usgs how did you manage to circumvent that on conda?

PS: I asked the author [here](https://github.com/RDFLib/sparqlwrapper/issues/46) as well.

**Comment by rsignell-usgs** [comment]
@ocefpaf, I can't remember how I circumvented it.   Did you figure this out?

**Comment by ocefpaf** [comment]
PR #36 provides a workaround until they fix this upstream (https://github.com/RDFLib/rdflib/issues/391).
