### ISSUE TITLE
octant version?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#172]
@rsignell-usgs help!

- `setup.py` says 0.1.0: https://github.com/hetland/octant/blob/master/setup.py#L66
- `__init__.py` says 0.2.0: https://github.com/hetland/octant/blob/master/octant/__init__.py#L29
- Our conda package says 0.8.dev(!): https://github.com/ioos/conda-recipes/blob/master/octant/meta.yaml#L3
- The latest release says 0.7.0: https://github.com/hetland/octant/releases

**Comment by ocefpaf** [comment]
Maybe @hetland can help sort this out?

**Comment by hetland** [comment]
I suspect those version numbers were made with a random number generator. I would take the most recent that is in octant itself, 0.7.0, and keep that. I have been bad at advancing the numbers with releases, but can now start afresh with 0.7.0.

**Comment by ocefpaf** [comment]
@hetland thanks!

Do you mind tagging a v0.7.0 release on GitHub?  That way I can point the conda package to that source and have some "provenance" for the package.
