### ISSUE TITLE
Which repository should we use for sci-wms?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#173]
https://github.com/kwilcox/sci-wms.git or https://github.com/sci-wms/sci-wms

**Comment by kwilcox** [comment]
@ocefpaf https://github.com/sci-wms/sci-wms

**Comment by ocefpaf** [comment]
Thanks. I will update our recipe.
Em 13/04/2015 15:27, "Kyle Wilcox" <notifications@github.com> escreveu:
