### ISSUE TITLE
Can we see the total downloads from the ioos binstar channel?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/conda-recipes#182]
It would be a nice if we could determine the total number of package downloads from the IOOS binstar channel.    I'm sure @dpsnowden would like to know, perhaps as info for the IOOS Z-gram. 

I can see individual package downloads on pages like this:
https://binstar.org/IOOS/cartopy/files
but don't know how to get the overall stats for the channel.

**Comment by ocefpaf** [comment]
You read my mind.  I have an draft email for continuum with that question (I was thinking about a 5 minutes talk at PyCon about it).

**Comment by ocefpaf** [comment]
Until we have a better solution lets just scrape the IOOS binstar webpage:

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/ocefpaf/40dd24132dc9618c0fb6/raw/2091c3a090b84578cfe39687416b3cae6baa74b9/scrape_binstar_download.ipynb
