### ISSUE TITLE
Problem building rtree 0.8.1 on RHEL6

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/conda-recipes#184]
I'm having a problem building `rtree-0.8.1` on RHEL6:
```
BUILD START: rtree-0.8.1-py27_0
Fetching package metadata: ..........
Solving package specifications: .
The following NEW packages will be INSTALLED:

    libspatialindex: 1.8.5-0      ioos-rhel6
    openssl:         1.0.1k-1     defaults
    pip:             6.0.8-py27_0 defaults
    python:          2.7.9-2      defaults
    readline:        6.2-2        defaults
    setuptools:      15.0-py27_0  defaults
    sqlite:          3.8.4.1-1    defaults
    system:          5.8-2        defaults
    tk:              8.5.18-0     defaults
    zlib:            1.2.8-0      defaults

Removing old work directory
Cloning into bare repository '/home/testbed/anaconda/conda-bld/git_cache/__github.com_Toblerity_rtree.git'...
remote: Counting objects: 1589, done.
remote: Total 1589 (delta 0), reused 0 (delta 0), pack-reused 1589
Receiving objects: 100% (1589/1589), 338.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1022/1022), done.
Checking connectivity... done
checkout: u'0.8.1'
Cloning into '/home/testbed/anaconda/conda-bld/work'...
done.
Checking connectivity... done
Note: checking out '0.8.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 871eb12... increment version to 0.8.1 in preparation for release
==> git log -n1 <==

commit 871eb120fa92292863909e1ce825beb37d10526f
Author: Howard Butler <howard@hobu.co>
Date:   Sun Nov 2 21:20:21 2014 -0600

    increment version to 0.8.1 in preparation for release


==> git describe --tags --dirty <==

0.8.1


==> git status <==

# HEAD detached at 0.8.1
nothing to commit, working directory clean


Package: rtree-0.8.1-py27_0
source tree in: /home/testbed/anaconda/conda-bld/work
+ /home/testbed/anaconda/envs/_build/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import rtree
  File "/home/testbed/anaconda/conda-bld/work/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/testbed/anaconda/conda-bld/work/rtree/index.py", line 34, in <module>
    raise Exception("This version of Rtree requires libspatialindex 1.7.0 or greater")
Exception: This version of Rtree requires libspatialindex 1.7.0 or greater
Command failed: /bin/bash -x -e /home/testbed/python/ioos/conda-recipes/rtree/build.sh
```
This is strange, since we have `libspatialindex-0.8.5` available in the IOOS-RHEL6 binstar channel:
https://binstar.org/ioos-rhel6/libspatialindex

Apparently `conda build` is finding a older version of `libspatialindex` somewhere, perhaps from the system, but why?

Here's the `conda info` which shows I only have the default channels and our `ioos-rhel6` channel:
 ```
[testbed@testbed2 ioos]$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/testbed/anaconda  (writable)
  default environment : /home/testbed/anaconda
     envs directories : /home/testbed/anaconda/envs
        package cache : /home/testbed/anaconda/pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/wakari/linux-64/
                        https://conda.binstar.org/t/<TOKEN>/wakari/noarch/
                        https://conda.binstar.org/t/<TOKEN>/ioos-rhel6/linux-64/
                        https://conda.binstar.org/t/<TOKEN>/ioos-rhel6/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/testbed/.condarc
    is foreign system : False
```

**Comment by rsignell-usgs** [comment]
@asmeurer, any idea why `conda build` is finding an older `libspatialindex` instead of using the one from our ioos channel?

**Comment by asmeurer** [comment]
It looks like rtree uses `ctypes.util.find_library` (https://github.com/Toblerity/rtree/blob/master/rtree/core.py#L105). Can you check what `find_library('spatialindex_c')` returns in the recipe?

**Comment by ocefpaf** [comment]
@asmeurer I cannot check it here, because my setup is different from the RHEL machine @rsignell-usgs is using, but that is probably the issue.  I faced that with other libraries as well.

We are OK when we use travis-ci, where we only install what we need, the problem surfaces when using local machines to build.

Is there a way to avoid programs picking up system installed libraries at build time?  Or do you suggest a patch like [this](https://github.com/ioos/conda-recipes/blob/master/shapely/osx-geos.patch#L21)?

**Comment by asmeurer** [comment]
You should definitely avoid hard-coded paths (that patch you showed is the right kind of thing, although it fixes OS X). I am actually curious what find_library() does. From the documentation, it seems like it might do the right thing, but I can't be sure.

**Comment by rsignell-usgs** [comment]
```
In [1]: from ctypes.util import find_library

In [2]: print find_library('spatialindex_c')
libspatialindex_c.so.1
```
```
[testbed@testbed2 ~]$ locate libspatialindex_c.so.1
/usr/lib/libspatialindex_c.so.1
/usr/lib/libspatialindex_c.so.1.0.0
```

**Comment by asmeurer** [comment]
Does that mean your package doesn't have the .so?

**Comment by rsignell-usgs** [comment]
Our package has libspatialindex as a requirement, and has
```
$PREFIX/lib/libspatialindex_c.so
```
so it seems to me that `find_library

**Comment by ocefpaf** [comment]
In my case (a modern Linux distro, not RHEL) `find_library` **does not** find the conda packaged `libspatialindex`.  I know that it exists:

```bash
$ locate libspatialindex_c.so
/home/filipe/miniconda/envs/SECOORA/lib/libspatialindex_c.so
/home/filipe/miniconda/envs/SECOORA/lib/libspatialindex_c.so.4
/home/filipe/miniconda/envs/SECOORA/lib/libspatialindex_c.so.4.0.1
/home/filipe/miniconda/pkgs/libspatialindex-1.8.5-0/lib/libspatialindex_c.so
/home/filipe/miniconda/pkgs/libspatialindex-1.8.5-0/lib/libspatialindex_c.so.4
/home/filipe/miniconda/pkgs/libspatialindex-1.8.5-0/lib/libspatialindex_c.so.4.0.1
```

but (from that conda env):
```python
print(find_library('spatialindex_c'))
None
```

and if I try to import `rtree` I get the `undefined symbol: Error_GetLastErrorNum`, probably due to the broken link.  The weird thing is that everything works fine during the build on travis-ci: https://travis-ci.org/ioos/conda-recipes/builds/56967192#L561.

@asmeurer is there a way to make conda packages, that use `find_library`, smarter?  Or should I just create a patch* and forget about it?

*The patch would hardcode `os.path.join(sys.prefix, 'lib', 'libspatialindex_c.{dylib,dll,so}')` instead of using `find_library`.

**Comment by asmeurer** [comment]
We need to figure out why find_library doesn't work ([here](https://hg.python.org/cpython/file/283036fe48e2/Lib/ctypes/util.py) is the source), so we can fix it.

**Comment by rsignell-usgs** [comment]
@ocefpaf , did we figure out a workaround here?  
I still can't build rtree because of this problem.

**Comment by ocefpaf** [comment]
Working on it.  I am creating a Centos VM to test the patch before sending the a PR.

**Comment by pelson** [comment]
Want a VM? You can try my centos 6 docker images if you like: https://registry.hub.docker.com/u/pelson/conda64_obvious_ci/ & https://registry.hub.docker.com/u/pelson/conda32_obvious_ci/

**Comment by ocefpaf** [comment]
I postponed learning docker for a while and now I think it is time to bite the bullet and do it.

Thanks!

**Comment by pelson** [comment]
> I postponed learning docker for a while and now I think it is time to bite the bullet and do it.

Enjoy! Their docs are pretty good.

**Comment by ocefpaf** [comment]
@rsignell-usgs can you test [this](https://binstar.org/ocefpaf/rtree) rtree on your RHEL6 machine?

Here is what I did:

```bash
docker pull pelson/conda64_obvious_ci
docker run -it --rm -v $(pwd):/home pelson/conda64_obvious_ci /bin/sh
conda config --add channels ioos -f
cd home
conda build rtree
```

 (Bare in mind that I just learned how to use docker :wink:):

NB: the `$pwd` variable is my cloned directory with the recipes.  If that works I can take over RHEL6 as a maintainer.

**Comment by pelson** [comment]
Told you it was magical! Awesome work @ocefpaf. :+1:

**Comment by ocefpaf** [comment]
Yeah.  Docker is quite powerful.   I feel silly for waiting so long to try it.

(The problem is that now I want to dockerize everything :grin:)

**Comment by rsignell-usgs** [comment]
@ocefpaf  And why is wanting to dockerize everything a bad thing? :smiley:

**Comment by rsignell-usgs** [comment]
I tried this on the RHEL6 system:
```
[testbed@testbed2 ~]$ conda install -c https://conda.binstar.org/ocefpaf rtree
Fetching package metadata: ..........
Solving package specifications: .
Package plan for installation in environment /home/testbed/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.6.2             |           py27_0         593 KB  defaults
    rtree-0.8.1                |           py27_0          26 KB  ocefpaf
    conda-3.11.0               |           py27_0         167 KB  defaults
    ------------------------------------------------------------
                                           Total:         786 KB

The following NEW packages will be INSTALLED:

    rtree:      0.8.1-py27_0  ocefpaf

The following packages will be UPDATED:

    conda:      3.10.1-py27_0 defaults --> 3.11.0-py27_0 defaults
    requests:   2.6.0-py27_0  defaults --> 2.6.2-py27_0  defaults
    setuptools: 15.0-py27_0   defaults --> 15.1-py27_1   defaults

```
and then tried it in ipython:
```
[testbed@testbed2 ~]$ ipython
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Mar  9 2015, 16:20:48)
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import rtree
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-41eaa719a642> in <module>()
----> 1 import rtree

/home/testbed/anaconda/lib/python2.7/site-packages/Rtree-0.8.1-py2.7.egg/rtree/__init__.py in <module>()
----> 1 from .index import Rtree
      2
      3 from .core import rt
      4
      5 __version__ = '0.8.1'

/home/testbed/anaconda/lib/python2.7/site-packages/Rtree-0.8.1-py2.7.egg/rtree/index.py in <module>()
     32
     33 if (major_version < 2 and minor_version < 7):
---> 34     raise Exception("This version of Rtree requires libspatialindex 1.7.0 or greater")
     35
     36 __all__ = ['Rtree', 'Index', 'Property']

Exception: This version of Rtree requires libspatialindex 1.7.0 or greater

In [2]: exit
```

**Comment by ocefpaf** [comment]
I am fixing that by building everything on the docker container, it should be ready soon.

**Comment by ocefpaf** [comment]
**Short version:** PR #198 fix this issue.

**Long version:** All python modules that uses `ctypes.util.find_library` will fail with conda.  They will either find a system wide library, instead of the conda counterpart, or they won't find anything.  (In rtree's case it is `spatialindex_c`.)

The best approach to fix this would be to fix `find_library` and it can play nice with conda.  Meanwhile the work-around is to patch the packages as we go.

In this particular case I hard-coded the conda lib path to force tha package to always find the conda `libspatialindex` version.

@rsignell-usgs [my user channel](https://binstar.org/ocefpaf) now has the OSX and RHL6 (actually Centos) packages.   I just tested them on Wakari successfully with the GLIBC error.

If you test them in your RHEL6 machine let me know.  That way I can start using the docker image to populate the RHEL6 channel.
