### ISSUE TITLE
mingwpy

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#185]
@rsignell-usgs and @pelson

This project https://bitbucket.org/carlkl/mingw-w64-for-python/downloads is moving to github https://github.com/mingwpy.  (And soon it will be getting some "wheels" and conda)

We should check it out to get gcc, gfortran and etc for Windows.

See https://us.pycon.org/2015/schedule/presentation/377/

**Comment by pelson** [comment]
Cool! Thanks for sharing @ocefpaf.

**Comment by rsignell-usgs** [comment]
@ocefpaf , the abstract says "show how to embed third party dynamic libraries (.dylib or .dll) in a wheel package on OSX and Windows to make it independent of non-Python dependencies,"   

Does that mean that Wheels can have all the functionality of Conda?

**Comment by ocefpaf** [comment]
@rsignell-usgs that means conda has all the functionality of wheels :wink: 
However, wheels binaries are not relocatable like conda binaries.

**Comment by ocefpaf** [comment]
BTW, just out of curiosity, Oliver Grisel showed me an all Linux solution for windows packages using wine+mingwpy instead of AppVeyor!

**Comment by pelson** [comment]
> Oliver Grisel showed me an all Linux solution for windows packages using wine+mingwpy instead of AppVeyor!

Goodness. I can feel the maintenance headache already :smile: 

> Does that mean that Wheels can have all the functionality of Conda?

I'm still a little bothered that we will end up with big wheels that ship all of the binaries that a package depends on, only to duplicate the binaries in other wheels (e.g. shapely and cartopy both depend on GEOS). That said, there are some benefits from the wheel approach - most notably for me is the ability to pip install into any Python installation (even conda), where conda distributions can only be installed (comfortably) into conda environments.

**Comment by ocefpaf** [comment]
> Goodness. I can feel the maintenance headache already

You have to admit that was a creative solution :wink:,  but I believe we are OK with AppVeyor.  Their reason for looking into this is speed.  AppVeyor is slow for their use case.  We are just shipping while they are build+testing every PR.

> duplicate the binaries in other wheels

Yes, PyPI+pip should think ~~out~~inside the box and do what other package managers already do.  Or just reduce its use to pure python packages.

**Comment by ocefpaf** [comment]
PR #393 closes this.  Now I will tackle one-by-one of the Python modules that need gfortran/gcc.  @rsignell-usgs `octant` is already in!
