### ISSUE TITLE
Customizing Ipython environment on Linux 

### ISSUE THREAD

**Issue by tarankalra** [ioos/conda-recipes#191]
I had added these two lines to customize the Ipython environment on my Linux machine in the "ipython_notebook_config.py" file 
with the help of this link "https://github.com/ioos/conda-recipes/wiki/Customizing-the-notebook-settings"

1. c.NotebookApp.notebook_dir = '/home/gadar/Documents/Notebook' 
to directly access the notebook folder 
2. c.FileNotebookManager.save_script = True
to save a .py equivalent of .ipynb file. 

These changes do not seem to come into effect. Is there an equivalent of "source.bashrc" to save these changes ?

**Comment by ocefpaf** [comment]
Hi @tarankalra,

-  First try `ipython locate profile`, from your `conda env` or `conda root installation`, to find where your ipython config files are.

- Check if you are adding these modification to those files.

- I recommend to create a new profile, to avoid messing up with the default, see the instruction here:
https://ipython.org/ipython-doc/dev/config/intro.html

Hope that helps,

-Filipe

**Comment by tarankalra** [comment]
Thanks Filipe. I had done the first two steps that you mentioned earlier. 

I will create a new profile now and check if the changes make the environment customized.

**Comment by tarankalra** [comment]
I created my own profile and edited the config.py file. I still don't see the changes being coming into effect.

**Comment by tarankalra** [comment]
Hi Filipe, 

@rsignell-usgs helped me figure out the issue. I had to do the last step that I missed in order for changes to come into life ie. " ipython notebook --profile=taran" (taran being my profile name)

**Comment by ocefpaf** [comment]
Great!  I was going to suggest a gtalk meeting to solve it.
