### ISSUE TITLE
sci-wms

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#193]
The latest sci-wms is 0.0.2, but somehow the previous version was tagged 0.1.0

https://binstar.org/IOOS/sci-wms-deps/files

Forcing conda to install the older version.

@rsignell-usgs we can delete the 0.1.0 binaries from the binstar channel, but I wanted to ask you first if that is OK.

**Comment by rsignell-usgs** [comment]
I would argue that 0.0.2 is not a valid release number!    How about 0.2.0 instead!

**Comment by rsignell-usgs** [comment]
But yes, go ahead and delete the 0.1.0 binaries.

**Comment by ocefpaf** [comment]
> I would argue that 0.0.2 is not a valid release number! How about 0.2.0 instead!

Agreed, but that is up to sci-wms devs.

> But yes, go ahead and delete the 0.1.0 binaries.

Done: https://binstar.org/ioos/sci-wms-deps
