### ISSUE TITLE
nco

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#221]
@ChrisBarker-NOAA is this something that you might want to take a look?

- [X] nco
    - [X] nco-bindings
    - [X] pyaxiom

**Comment by ChrisBarker-NOAA** [comment]
NCO -- yes

pyaxium -- that's the first I've heard of it -- but it looks like it's got some good stuff.

But when is the question -- not today ;-)

**Comment by ChrisBarker-NOAA** [comment]
Actually, it will be at least a few days -. My Mac is dead :-)

CHB

On May 5, 2015, at 11:38 AM, Filipe <notifications@github.com> wrote:

@ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> is this something
that you might want to take a look?

   -  nco
      -  nco-bindings
      -  pyaxiom

—
Reply to this email directly or view it on GitHub
<https://github.com/ioos/conda-recipes/issues/221>.

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA don't worry.  `nco` is a nice package to have in the channel, but I guess that most OSX users already have it installed via other methods.

**Comment by ocefpaf** [comment]
BTW we only need `nco`, `pyaxiom` and `nco-bindings` are pure python modules that depend on nco.

**Comment by ocefpaf** [comment]
Fixed in #285
