### ISSUE TITLE
Add Linux32...

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#231]
... not because we need them, but it is so easy to do it with @pelson's docker image :wink:

**Comment by rsignell-usgs** [comment]
Agreed.  Why not!?

**Comment by ocefpaf** [comment]
Done!

https://binstar.org/IOOS/iris/files

**Comment by rsignell-usgs** [comment]
nice!

**Comment by pelson** [comment]
Swish! :+1: 

I love docker. :smile:
