### ISSUE TITLE
Python3 binaries

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#323]
I am  ~~procrastinating~~ experimenting with Python 3 builds in [this branch](https://github.com/ocefpaf/conda-recipes/tree/linux_py3) and the binaries are available in my [channel](http://anaconda.org/ocefpaf).

@kwilcox I am reluctant to merge these changes into the IOOS channel.  Several of these binaries "compiled" with Python 3 but they will not work.  For example: [wicken](http://anaconda.org/ocefpaf/wicken/files) and [petulant-bear](http://anaconda.org/ocefpaf/petulant-bear/files) are not compatible with Python 3.  Yet the binaries were compiled and a broken package was uploaded to the channel.

I cannot afford to go through all the packages to check who works and who does work with Python 3 right now. In addition we still need to find a way to create a build matrix that skips non-Python 3 packages.

I strongly believe that it is time to invest our efforts in [conda-forge](https://github.com/conda-forge)!

(Pinging @pelson here to help.)

The concept is to have 1 package 1 repository.  That will not only facilitate contributions to the recipes, avoiding redundant efforts, but the build matrix issue above just goes away.

Meanwhile here is what we can do: Can you provide me a list of the "urgent" packages you need in Python 3?  I will test and copy only those binaries to the IOOS channel.

**Comment by ocefpaf** [comment]
Here are the packages I removed from that branch (known non-Python 3) :

- [ ] utilities [iris] 
- [ ] ulmo [suds]
- [ ] tardis [iris]
- [ ] suds
- [ ] pytest-cov
- [ ] pyhum
- [ ] pygdp
- [ ] pycsw
- [ ] pyaxiom [:eyes: at you @kwilcox]
- [ ] paegan-transport
- [ ] optcomplete
- [ ] octant
- [ ] oceans [iris]
- [ ] iris
- [ ] github3.py [NB: the docs says it should work...]
- [ ] geojsonio [github3.py]
- [ ] ecmwf_grib [There is a patch in scitools-conda-recipes]
- [ ] compliance-checker
- [ ] cf_units [Argh! I need to get back to my PR!!]

**Comment by kwilcox** [comment]
I'm working on switching to py3 universally. I just bumped `pyaxiom` to support py3 on the master branch (version 1.0.0) and `pyncml` supports py3 as of 0.0.8.  Those are the two I need now.

**Comment by kwilcox** [comment]
@ocefpaf If you need any help with `conda-forge`, count me in!

**Comment by pelson** [comment]
@kwilcox - yes - that would be awesome!
Still very early days but: https://github.com/conda-forge/. There are some tasks in https://github.com/conda-forge/conda-forge.github.io/issues and the main cookie-cutter library is in https://github.com/conda-forge/conda-smithy.

**Comment by ocefpaf** [comment]
> I'm working on switching to py3 universally. I just bumped `pyaxiom` to support py3 on the master branch (version 1.0.0) and `pyncml` supports py3 as of 0.0.8.  Those are the two I need now.

@kwilcox `pyaxiom` still needs some work (see https://github.com/axiom-data-science/pyaxiom/pull/3), but its dependencies (`nco-bindings` and `pyncml`) are already on the IOOS channel (both Python 3.3 and 3.4).  [Travis](https://travis-ci.org/ocefpaf/pyaxiom/builds/73367872) is  running now!

**Comment by ocefpaf** [comment]
New plan.  [Latest obvious-ci](https://github.com/pelson/Obvious-CI/pull/17) can deal with a build matrix.  Now we need to:
- Create two directories (or maybe 3?): `python2`, `python3` (another one for `non-python-packages`?)
- Using the CIs to enter each directory and fire up `obvci_conda_build_dir.py` with `--build-condition="python >=2.7"` and `--build-condition="python >=3.4"` respectively.

**Comment by QuLogic** [comment]
You can use `suds-jurko` instead of `suds`, though I think both of them are dead. `pytest-cov`'s wheel is marked `py2.py3` on PyPI, so I think it should work as well. I'm pretty sure I've used `github3.py` on Python 3 and `geojsonio` is tested on Python 3 on Travis.

**Comment by ocefpaf** [comment]
Thanks @QuLogic!

@kwilcox can you take a look `suds` -> `suds-jurko` works for you?

The rest should be OK.  I remembering running them over the weekend... but I need to get back to this.

**Comment by ocefpaf** [comment]
PR #388 fixes this!
