### ISSUE TITLE
Revert submodules

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#34]
@rsignell-usgs and I had this conversation thread in a SECOORA repo.  I am moving it here:

@ocefpaf
> Our owslib is inside the conda-recipes-scitools submodule. The version they are using is pinned to 0.8.7 which was OK for my use until now (my scripts did not work with owslib > 0.8.9, but that is resolved now.)

> Maybe adding conda-recipes-scitools as a submodule was not a good idea... Do you want me to revert it and update the packages?

@rsignell-usgs 
> Yeah, I think that probably is a good idea. I like being in control of our packages.  :grinning:

**Comment by ocefpaf** [comment]
PR #33 should fix #34.

**Comment by rsignell-usgs** [comment]
Fixed by #33.
