### ISSUE TITLE
rasterio dependencies

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/conda-recipes#35]
I'm having trouble building the latest rasterio 0.16 as a conda module.   I see that the requirements have changed -- @sgillies or @brendan-ward, do these build and run requirements for the conda-recipe look correct: https://github.com/ioos/conda-recipes/blob/master/rasterio/meta.yaml#L28-L53

**Comment by sgillies** [comment]
@rsignell-usgs Rasterio's setup.py (or requirements.txt) is the authority for runtime requirements: https://github.com/mapbox/rasterio/blob/master/setup.py#L158-L165. Its requirements-dev.txt file includes requirements of the continuous integration and wheel building environments. You won't need coveralls, pytest, delocate, or wheel.

Hey, speaking of conda packages, what do you do for GDAL? The one in ContinuumIOs official channel is useless.

**Comment by rsignell-usgs** [comment]
@sgillies, so the setup says:
```
# Runtime requirements.
inst_reqs = [
    'affine>=1.0',
    'cligj',
    'Numpy>=1.7' ]

if sys.version_info < (3, 4):
    inst_reqs.append('enum34')
```
while the requirements.txt say:
```
affine
cligj
enum34
numpy>=1.8.0
setuptools
```
so a couple of questions:

* do we need numpy >1.7 or numpy > 1.8?
* I don't see "cython" or "gdal" listed as requirements, but don't we need those also?
* for conda, which are "build" requirements, and which are "run" requirements?

Regarding your last question about gdal, happy news:
Osgeo has a  binstar channel:
https://binstar.org/osgeo/gdal
so you can install with:
https://conda.binstar.org/osgeo

-Rich

**Comment by sgillies** [comment]
* Numpy >= 1.7 is fine
* Cython is only used to create C code from the .pyx files, pre-compilation. It's not needed at run time.
* Rasterio needs the GDAL C library, but that can't be expressed in setuptools/distutils. Rasterio doesn't use GDAL's Python bindings at all.
* For conda, Cython is the one build requirement on top of the run time requirements.

I'm still finding it hard to appreciate conda, so I'm glad you're interested in keeping Rasterio up to date. Are you putting Rasterio packages in a particular channel?

/cc @kapadia

**Comment by dharhas** [comment]
@rsignell-usgs You got me all excited about GDAL in the OSGeo channel but its Mac and Linux only. Windows is where we have the most pain. We are still having to kludge conda + windows binaries from http://www.lfd.uci.edu/~gohlke/pythonlibs/ to get things working.

**Comment by brendan-ward** [comment]
While being a Windows user, I don't use conda, but I wonder if there is a combination using appveyor ( [example here](https://github.com/rmcgibbo/python-appveyor-conda-example) ) to help with this.  Work going on for appveyor integration in rasterio [#260](https://github.com/mapbox/rasterio/issues/260).  Maybe it's a matter of adding in a conda build step and deploying to binstar?  

I'm clearly out of my domain here - does anyone here know more about integrating that workflow?

**Comment by rsignell-usgs** [comment]
@dharhas and @brendan-ward, the main problem here on Windows is that the gdal conda package is missing the include directory (as well as the share directory), so anything that depends on gdal is problamatic.   I've asked Continuum for help here: https://github.com/conda/conda-recipes/issues/211#issuecomment-72196103 and I've also pinged kitware to see if  they have a Cmake configuration for gdal available that would allow us to build a windows gdal package more easily.

**Comment by dharhas** [comment]
@rsignell-usgs the same problem exists with the continuum conda package on osx. Kitware is under contract to us (at my new USACE job) to build some other stuff so I'm talking to them weekly. A couple of days ago they were saying they were have trouble some issues building the latest GDAL, something about memory leaks. I think the version included in paraview currently is 1.8.

**Comment by rsignell-usgs** [comment]
@dharhas, cool.   @aashish24, please feel free to update us here!

**Comment by ocefpaf** [comment]
@rsignell-usgs rasterio is building fine for Linux now:

http://nbviewer.ipython.org/gist/ocefpaf/cdf3cfc632763b1757bf

Can we close this issue and open another one for the windows binary?

**Comment by rsignell-usgs** [comment]
Sure.

**Comment by rsignell-usgs** [comment]
@aashish24 pointed me toward a CMAKE-driven GDAL here:
https://github.com/nextgis/gdal_svn/tree/cmake4gdal
