### ISSUE TITLE
No baked numpy

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#360]
`conda-build` was [updated](https://github.com/conda/conda-build/pull/493) to treat numpy like any other package.  If we want to specify a numpy version now (e.g.: due to a specific ABI) we have to do it explicitly like `numpy ==1.8`.

One side effect is that our package that depends on `numpy` got re-built with a `nppy27` suffix instead of `np19py27` .

I do not know how `conda` will behave with packages that have the **same version** and the **same build number**, but **different** numpy dependencies during updates/new-installs.

**Comment by pelson** [comment]
> I do not know how conda will behave with packages that have the same version and the same build number, but different numpy dependencies during updates/new-installs.

Interesting question. If I was guessing, I'd say that first of all the order of the channel was considered, then the string ordering of nppy27 vs np19py27. Ping @asmeurer.

**Comment by ocefpaf** [comment]
The string order of `sorted(['nppy27', 'np19py27'])` is `['np19py27', 'nppy27']`.  Not intuitive but also not what we want.  We want the "new" build, without the numpy version, to be the default.

Conda is doing the right thing:

```
$ conda install biggus
Fetching package metadata: ......
Solving package specifications: .................
Warning: 2 possible package resolutions (only showing differing packages):
        [u'biggus-0.11.0-nppy27_0.tar.bz2'],
        [u'biggus-0.11.0-np19py27_0.tar.bz2'],

Package plan for installation in environment $/HOME/miniconda/envs/main:

The following packages will be UPDATED:

    biggus: 0.11.0-np19py27_0 ioos --> 0.11.0-nppy27_0 ioos
```

**Comment by asmeurer** [comment]
conda does use the build string to break ties, but it also gives a warning in that instance, as you saw above. I recommend always bumping the build number when you rebuild a package. It will avoid this situation entirely.

**Comment by asmeurer** [comment]
And channel ordering is only used for packages that have the exact same file name.

**Comment by ocefpaf** [comment]
Thanks @asmeurer.

> I recommend always bumping the build number when you rebuild a package.

I always do, but in this case it is too late for that.  All of our packages got re-build after a `conda-build` update in our build "farm."  No big deal though.

> And channel ordering is only used for packages that have the exact same file name.

It would be nice to have some sort of control over this.  Like a channel "score" or something in the `.condarc`.
