### ISSUE TITLE
Test pyke and iris on Python3

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#391]
I am unsure if `pyke` will work properly.  The package builds just fine,

http://anaconda.org/SciTools/pyke/1.1.1/download/linux-64/pyke-1.1.1-py34_0.tar.bz2

but there is a lot of Python2 specific code in there.

**Comment by pelson** [comment]
Agreed. I don't know if @qulogic has looked at pyke for py3?

**Comment by QuLogic** [comment]
There's a separate [download for pyke3](http://pkgs.fedoraproject.org/cgit/pyke.git/tree/pyke.spec#n14) that you need to use.

**Comment by ocefpaf** [comment]
Thanks @QuLogic.  I just sent #398 with that change.  Porting that to SciTools now.
