### ISSUE TITLE
ulmo available on binstar

### ISSUE THREAD

**Issue by dharhas** [ioos/conda-recipes#40]
Not exactly an issue, more an FYI. I just built the latest version of ulmo and published it for all platforms to binstar in the ulmo channel. I've tested on osx, win-32 and wakari and it seems to work fine. Please try it out and see if it works for you.

To install:

    conda install -c ulmo ulmo

**Comment by rsignell-usgs** [comment]
I tried it on Win 64 and
```
import ulmo
st = ulmo.ncdc.ghcn_daily.get_stations(country='GM', as_dataframe=True)
st.head()
```
worked just fine:

![2-2-2015 12-52-26 pm](https://cloud.githubusercontent.com/assets/1872600/6005724/8cdb2e58-aada-11e4-82fa-d6a130dda504.png)
