### ISSUE TITLE
Make use of obvious-ci  to build all packages for OSX, Linux and Windows.

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#42]
• Download the bootstrap:
`wget https://raw.githubusercontent.com/pelson/Obvious-CI/v0.1.0/bootstrap-obvious-ci-and-miniconda.py`

• Install obvious-ci (and miniconda) using the bootstrap:
`python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 -without-obvci`
`source ~/miniconda/bin/activate root`

• Install conda build
`obvci_install_conda_build_tools.py`

• Build everything in the directory:
`obvci_conda_build_dir.py conda-recipes rsignell-usgs --channel main`

Those steps can be inside a [.travis-ci](https://github.com/SciTools/conda-recipes-scitools/blob/master/.travis.yml) config file or [appveyor.yml](https://github.com/SciTools/conda-recipes-scitools/blob/master/appveyor.yml) automating the build on Linux and MacOS (via travis-ci) and windows (via Appveyor).

@rsignell-usgs I will show you the last step today, but lets keep this issue open and try to implement the rest as well.

**Comment by ocefpaf** [comment]
Before we do anything we need to merge #38.

**Comment by ocefpaf** [comment]
Travis is not building MacOS at the moment:

http://docs.travis-ci.com/user/multi-os/

**Comment by ocefpaf** [comment]
@rsignell-usgs here is how to create the TOKEN:

https://github.com/pyoceans/conda-recipes-pyoceans/wiki/Setup-travis-ci-build-upload

Let me know if you have any trouble.

PS: We might want to modify the `.travis.yml` to use IOOS channel and create the TOKEN with the IOOS binstar account.

**Comment by rsignell-usgs** [comment]
Let's definitely do this for the ioos organization on binstar.
I've added you as an owner at
https://binstar.org/organization/ioos/settings/groups/owners

**Comment by ocefpaf** [comment]
I am closing this issue* and opening two other to track the MacOS and Windows builds.

\*  The Linux builds should be OK with the last 3 PRs (#62, #55, and #50).  Now we need to advertise the [IOOS channel](https://binstar.org/ioos?filter=all) and get these packages tested.
