### ISSUE TITLE
Use AppVeyor's minconda

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#460]
It could reduce the build time a little bit, but I am not sure if it is advisable...

https://github.com/appveyor/ci/issues/359

**Comment by pelson** [comment]
Cool! Sounds great!

**Comment by ocefpaf** [comment]
Done in https://github.com/ocefpaf/conda-recipes/commit/83f288329ade15fcc89e59e1da1149aae94e6485
