### ISSUE TITLE
Exact requirements for macos and win64 but not linux?

### ISSUE THREAD

**Issue by emiliom** [ioos/conda-recipes#486]
The wiki instructions for linux use the [ioos_req.txt](https://github.com/ioos/conda-recipes/blob/master/00_env_requirements/ioos/ioos_req.txt) file that has no package version specification. I've used this successfully on multiple linux machines (all Ubuntu, BTW). 

But the macosx and windows64 instructions both use an "exact" req file (eg, [ioos_req_exact_mac_osx.txt](https://github.com/ioos/conda-recipes/blob/master/00_env_requirements/ioos/ioos_req_exact_mac_osx.txt)) that specifies exact package versions. Does the non-versioned requirements file not work on mac and windows?

A colleague of mine is trying to follow the IOOS wiki instructions for the first time, on macosx, and ran into this error when creating the IOOS env:
```
Fetching package metadata: ..
Error: No packages found in current osx-64 channels matching: binstar 0.10.1 py27_2
```
She's trying a couple of alternatives, but in the meantime I wanted to look into this a bit.

Thanks!

**Comment by ocefpaf** [comment]
Argh... We have to update those!  That was a workaround from the early days of the channels.  I am fixing this ASAP.  Thanks for the report!

**Comment by emiliom** [comment]
Oh, good! That's a relief. Thanks!
