### ISSUE TITLE
Proj4 package name

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#491]
The anaconda default channel names [Proj.4](https://trac.osgeo.org/proj/) as `proj.4` and we name it `proj4`.

Since we want to make use of the default channel as much as possible we should consider renaming ours, and eventually start using the default channel, to `proj.4`.

That will fix a few issues like having two proj4 packages installed when mixing default channel with our custom channels.

@pelson  What do you think?

**Comment by pelson** [comment]
Yep, let's give it a shot! :+1:
