### ISSUE TITLE
Numpy C-API

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#507]
A list of packages that depends on the numpy ABI and require the `numpy x.x` syntax

- [X] cartopy
- [X] ecmwf_grib
- [X] mo_pack
- [X] shapely
- [X] iris
- [X] netcdf4
- [X] octant
- [X] gdal
- [X] fiona
- [X] rasterio

**Comment by pelson** [comment]
Shapely?

**Comment by ocefpaf** [comment]
Not sure if baking the build string will help.  The [conda's docs says](http://conda.pydata.org/docs/spec.html)

> The build string is used to differentiate builds of packages with otherwise the same name and version, e.g. a build with other dependencies (like Python 3.4 instead of Python 2.7), a bug fix in the build process, or some different optional dependencies (MKL vs. ATLAS linkage), etc. Nothing in conda actually inspects the build string—strings such as np18py34_1 are only designed for human readability, but are never parsed by conda.

UPDATE: However, it seems that the statement above is not true.  So I am re-adding the numpy build strings to the IOOS channel.

**Comment by ocefpaf** [comment]
Outdated.
