### ISSUE TITLE
Add pyferret -- and enable Ferret awesomeness in Jupyter notebooks

### ISSUE THREAD

**Issue by emiliom** [ioos/conda-recipes#542]
I used to use [Ferret](http://ferret.pmel.noaa.gov/Ferret/home) ages ago [1]. It was then, and still is, an awesome application from NOAA PMEL (the Seattle gang; originally started by the almighty Steve Hankin, I think). It's also the backend visualization engine for [LAS (Live Access Server)](http://ferret.pmel.noaa.gov/LAS). Ferret syntax is fantastically expressive, if somewhat hard to get into initially.

I've known about [pyferret](http://ferret.pmel.noaa.gov/Ferret/documentation/pyferret) for a while, but never used it. I can't comment on how stable and comprehensive it is. But if it provides robust access to 90% of Ferret's functionality, it must be pretty nice, specially for Python people with Ferret experience. Here's a [2012 abstract on pyferret.](https://ams.confex.com/ams/92Annual/webprogram/Paper196835.html)

The kicker for me, that motivated me to suggest adding pyferret to the ioos conda-recipes, is the [IPython/Jupyter extension, "ipython-ferretmagic"](https://github.com/PBrockmann/ipython-ferretmagic). Check out the [demo notebooks](http://nbviewer.ipython.org/github/PBrockmann/ipython-ferretmagic/tree/master/). Mind blown! ![Mind blown!](https://raw.githubusercontent.com/helenvholmes/gifs/gh-pages/mind%20blown/cosmos.gif)

Consider this a stub for future reference. I can't offer to help with pyferret, since I'm not using it myself. It'd be interesting to see how many people use Ferret or LAS (and pyferret) in the community IOOS and friends, to see if this is worth anyone's time ...

[1] I even wrote the Textpad (MS Windows) syntax file for Ferret GO files, 14 years ago! [Search for "Ferret" on this listing of Textpad syntax files](http://www.textpad.com/add-ons/syna2g.html)

**Comment by ocefpaf** [comment]
Indeed kernels to access other languages from the notebook are awesome.

The problem is that build pyferret is not an easy task.  Starts with the source download 44.1 MB!!!  I am sure there is a lot of fat to cut there... I tried in the past and it depended on Ferret.  Ferret was not a trivial build.  (Maybe things changed since then.)

I will try to add it, but I don't want to give you too much hope that it will work.

**Comment by emiliom** [comment]
Ah. Thanks. Again, to be clear, I have no plans to use this in the near future. I don't use Ferret anymore, for better or for worse. But I wanted to mention it and document it here b/c it seemed like low-hanging fruit that could be of use to many people. Maybe it isn't so low hanging ... So, don't do it for me. Do it for the children (they're our future), and for the kittens.

**Comment by ocefpaf** [comment]
It is actually more complicated than I thought.
See http://ferret.pmel.noaa.gov/Ferret/documentation/pyferret/build-install/

You best chance is to use the pre-built binaries...

**Comment by ocefpaf** [comment]
@emiliom we are migrating to conda-forge. I will open an issue there for this request.
