### ISSUE TITLE
The following packages are failing in Python 3.5 and OSX

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#586]
- [X] `geopandas`:  unknown missing dependency (see #663)
- [X] `pygridgen`: `AttributeError: 'Gridgen' object has no attribute '_libgridgen'`
- [X] `pygridtools`: Needs `pygridgen`

ping @phobson I do not have an OSX machine to test what is going on with `pygridgen` on OSX+Python 3.5.  I suspect it is something simple that I am missing since Python 3.4 works just fine.

**Comment by phobson** [comment]
I'll look this weekend. 



—

**Comment by ocefpaf** [comment]
Thanks!

**Comment by phobson** [comment]
ok -- my pygridgen branch is now building on Travis in python 3.5. I put up a new "v0.1.1" release to reflect this.

**Comment by ocefpaf** [comment]
Thanks!   I will test that release ASAP.
