### ISSUE TITLE
link nco with ESMF

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#604]
Ping @bekozi 

If I understand correctly the latest nco can use ESMF.  I will  try to re-compile out version linking with the ESMF package you submitted.

**Comment by bekozi** [comment]
There is an issue related to this on the NCO SourceForge: http://sourceforge.net/p/nco/discussion/9831/thread/ce5e30ef/. I'm not sure if it will affect the conda build and linking. It is worth being aware of though. Thanks for the ping.

I'm going to be sending another PR your way shortly for osx ESMF builds. I'm also going to add a command for running an ESMF test subset.

**Comment by ocefpaf** [comment]
> There is an issue related to this on the NCO SourceForge

Good to know.  I just opened this issue to keep track of it.

> I'm going to be sending another PR your way shortly for osx ESMF builds.

Awesome! Thanks.

**Comment by ocefpaf** [comment]
Doing this at conda-forge.
