### ISSUE TITLE
Fiona fails to open shapefiles (Geopandas/Fiona/GDAL)

### ISSUE THREAD

**Issue by fmaussion** [ioos/conda-recipes#623]
I hope this is the right place to describe the problem.

All my attempts to make Geopandas work correctly with conda failed on Linux, Windows and on Mac OSX.

```
conda create -n conda_test python=2.7
source activate conda_test
python 
```

```python
>>> import geopandas
>>> geopandas.read_file('/home/mowglie/disk/Data/GIS/SHAPES/world_borders/world_borders.shp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mowglie/.bin/conda/envs/oggm_conda_test/lib/python2.7/site-packages/geopandas/io/file.py", line 20, in read_file
    gdf = GeoDataFrame.from_features(f, crs=crs)
  File "/home/mowglie/.bin/conda/envs/oggm_conda_test/lib/python2.7/site-packages/geopandas/geodataframe.py", line 173, in from_features
    for f in features:
  File "fiona/ogrext.pyx", line 1080, in fiona.ogrext.Iterator.__next__ (fiona/ogrext.c:17244)
  File "fiona/ogrext.pyx", line 161, in fiona.ogrext.FeatureBuilder.build (fiona/ogrext.c:3254)
IndexError: list index out of range
```
The problem is unrelated to the shapefile and/or the python version. I wonder if the problem doesn't occur at the GDAL level already.

Thanks for any tip.

**Comment by fmaussion** [comment]
sorry for the noise. Seems to be related to certain shapefiles, some can be opened.

**Comment by ocefpaf** [comment]
No problem.  The issue does exist because fiona is not 100% OK with `gdal 2.0.0`

Please try:

```shell
conda create -n conda_test python=2.7 geopandas
source activate conda_test
conda list | grep -E 'fiona|geopandas|gdal'
```

And you will see that you get:
```
fiona                     1.6.0               np110py27_0    defaults
geopandas                 0.1.1                    py27_1    ioos
libgdal                   2.0.0                         0    defaults
```

IMO the default channel is shipping a broken `fiona`.

The solution is to downgrade fiona, but that will bring all sort of pain due to numpy versions, etc. (Most packages are no longer compiled against numpy 1.9, forcing us to downgrade them all.)

This worked for me:

```shell
conda create -n conda_test python=2.7 geopandas numpy=1.9 gdal=1.11.2
```

Maybe we should package fiona here in IOOS instead of relying on the default channel  :unamused:

**Comment by fmaussion** [comment]
Thanks for your answer!

I think that it has something to do with Fiona on conda because my tests with pip / virtualenvs did work fine.

Your example did not work (geopandas ist not on standard codna channels) but this did the trick and opened the file without error:

```
conda create -n conda_test python=2.7
source activate  conda_test
conda install -c https://conda.anaconda.org/ioos geopandas numpy=1.9 gdal=1.11.2
```

How can I now install further packages like scipy *without* upgrading numpy? Conda always wants to upgrade everything...

**Comment by ocefpaf** [comment]
> I think that it has something to do with Fiona on conda because my tests with pip / virtualenvs did work fine.

It is.  Like I said the default channel builds fiona against `gdal 2.0.0` and that it not OK.
Did you get fiona fully working on your virtualenv with `gdal 2`?

> Your example did not work (geopandas is not available in the standard conda channels).

You still need to add the IOOS channel to get geopandas.  But note my comment above: **only** geopandas is coming from IOOS.  We rely on fiona from the default channel though.

> How can I now install further packages like scipy without upgrading numpy?

You can ask in the conda mailing list.  I would create an `environment.yml` file listing all you need and install all packages at the env creation.

Maybe one day continuum will fix fiona.  Keep your eye on https://github.com/ContinuumIO/anaconda-issues/issues/401

**Comment by fmaussion** [comment]
Thanks for the link! I managed to get things work by installing my packages and keeping a `numpy=1.9 gdal=1.11.2` at the end of all my conda install commands.

On my virtualenv I have gdal 1.10.0 installed (which is btw also not painless to install...)

**Comment by fmaussion** [comment]
For us the solution above (fixing versions to `numpy=1.9` and `gdal=1.11.2`) did work on Linux and Mac OS X but not on windows because of this issue: https://github.com/ContinuumIO/anaconda-issues/issues/295

Downgrading Fiona *after* having installed gdal seems to work:

```
conda install --force --yes --quiet fiona=1.5.1
```

**Comment by ocefpaf** [comment]
Thanks for the info!

**Comment by ocefpaf** [comment]
We are now packaging `gdal 1.11.3`, `fiona 1.6.2`.  `geopandas` is tested against them and I added a regression test (see #635) to prevent this problem from resurfacing.

@fmaussion and @jorisvandenbossche let me know if you can try these packages.  They should be in the channel soon.

**Comment by emiliom** [comment]
It's fantastic to see so much activity and progress in the ioos recipes/channel around the geospatial stack! The stopgap measures to distribute a working fiona conda package is great.

But how constructive is it to invest much energy into testing against the [official geopandas package on pypi](https://pypi.python.org/pypi/geopandas/0.1.1), when its code base is so old (it says on pypi that it was uploaded in Sept. 2014 -- probably eons ago in geopandas time), and the need for a new release [(0.2.0)](https://github.com/geopandas/geopandas/issues/242) based on the current master [has been](https://github.com/geopandas/geopandas/issues/252#issuecomment-157495932) widely [acknowledged](https://github.com/geopandas/geopandas/issues/237#issuecomment-153420047)? One major gap in the very old geopandas pypi package is that it doesn't have the `tools` module (including the `overlay` and `sjoin` tools -- majorly cool stuff!).

For now, it appears that the main way to install a contemporary geopandas is via the github repo on master. But I know @ocefpaf is reluctant to build conda packages based on repos (with good reason), and besides, [a 0.2.0 release is being worked on](https://github.com/geopandas/geopandas/issues/242). 

For what it's worth, on Thursday I tested creating a conda environment (on Ubuntu) with, first, all of geopandas' (github master) dependencies from conda packages, following @ocefpaf's instructions and other info out there, then pip installing geopandas from github:
```
conda create -n geopandas python=2.7 numpy=1.9 gdal=1.11.2 fiona shapely descartes pyproj rtree geojson ipython-notebook seaborn folium
source activate geopandas
pip install git+https://github.com/geopandas/geopandas.git
```
This was a bit of a trial and error, such as the need to include `rtree` explicitly. Obviously some of those packages are off topic (`ipython-notebook, seaborn, folium`), but I wanted them in there for testing! I specially wanted to test `tools.overlay` and `tools.sjoin`. That setup installed (among other things):
```
descartes                 1.0.1
fiona                     1.5.1
gdal                      1.11.2
libgdal                   1.11.2
pandas                    0.16.2
pyproj                    1.9.4
rtree                     0.8.2
shapely                   1.5.12
```
And `geopandas-0.1.0.dev` (looks to me like just outdated version labelling in [setup.py](https://github.com/geopandas/geopandas/blob/master/setup.py)). 

I then adapted the [overlays](https://github.com/geopandas/geopandas/blob/master/examples/overlays.ipynb) and [spatial_joins](https://github.com/geopandas/geopandas/blob/master/examples/spatial_joins.ipynb) example notebooks, to make them work (eg, needed to find and download the example shape file). Everything eventually worked great. Pretty exciting to see geopandas so capable and "easily" installed! FYI, my notebooks are [here](https://github.com/emiliom/stuff/blob/master/geopandas_overlays.ipynb) and [here](https://github.com/emiliom/stuff/blob/master/geopandas_spatial_joins.ipynb). 

Can't wait to have a geopandas 0.2.0 on the ioos channel installing cleanly with all its dependencies off the bat. In the meantime, in my opinion:
- Getting fiona packaged on the ioos channel, to get around the gdal 2 problem: awesome (and almost done, based on @ocefpaf's latest flurry of work!)
- Testing against the old pypi geopandas: waste of time, until 0.2.0 is out?

**Comment by jorisvandenbossche** [comment]
@ocefpaf Great! 
I tested it by installing a clean env for python 2 with just
```
conda create -n geopandas_test -c ioos geopandas
```

and it seems to work. Also pyproj works (it is installed from the ioos channel, but `proj4` is still installed from the default channel). Fiona is installed from the ioos channel for py2.7 (fiona 1.6.2), and this works.

For python 3 a bit more problems, installed this in a clean env with:

```
conda create -n geopandas_test2 -c ioos geopandas python=3
```

but here fiona is installed from the default channel for py3.4 (fiona 1.5.1). Although it is 1.5.1 that is installed together with gdal 1.11.2 (so not 2.0), it gave a DLL load failed error. With `conda install -c ioos fiona` this is solved. 
But for the initial env creation, I though adding fiona explicitly would solve it: `conda create -n env -c ioos geopandas fiona python=3`, but that still tries to install fiona from the default channel. Is there a way to do this in one step? (or but not that difficult to do it in two steps)

Anyway, this will make the install instructions much shorter! (https://github.com/geopandas/geopandas/issues/237#issuecomment-151106795)

@emiliom I fully agree that we should try to get a new geopandas release, but as far as I know, this is a bit orthogonal to this issue. It's not geopandas itself that is difficult to install, whether it is for the released version or the master version (it's a pure python package), but it are the dependencies of it that cause(d) the trouble. Having a new geopandas release will not change this. And the testing that is done here, is just reading a shapefile I think, which actually tests that fiona is linked OK, and this has not changed a lot since 0.1 I think.

**Comment by ocefpaf** [comment]
> But how constructive is it to invest much energy into testing against the official geopandas package on pypi

It real problem as `fiona` and `gdal 2`  geopandas (old or new) would still be a victim of that packaging bug.  

PS0: The official release rule can be broken (and I have several times) when we have a dire need for latest features.  But I guess we won't need one for geopandas.  I believe a new release will be out soon.

PS1: Did not know about `overlays` and `spatial_joins` coold stuff indeed.

**Comment by ocefpaf** [comment]
>  but proj4 is still installed from the default channel).

That should not be a problem.  Our `pyproj` uses its bundled source.  (It is just a waste of disk space, but who cares about that nowadays :wink:)

> For python 3 a bit more problems

Windows, Linux or OSX?  I just tested,

```bash
conda create -n geopandas_test2 -c ioos geopandas python=3
```

on Linux and I got Python 3.5 instead of 3.4 and the "correct" `gdal`/`fiona`/`geopandas` stack.  I will test it on Windows as soon as possible.  Note that we do not have that stack properly packaged for OSX!  (See #629)

> With `conda install -c ioos fiona` this is solved.

OK.  I am assuming that is not OSX then.  Still weird...  Conda's dependency solver is puzzling sometimes.

> Is there a way to do this in one step?

Nope.  It should work...  Not sure what happened there.

> Having a new geopandas release will not change this. And the testing that is done here, is just reading a shapefile I think, which actually tests that fiona is linked OK, and this has not changed a lot since 0.1 I think.

Also, adding regression tests never hurt anyone :stuck_out_tongue_winking_eye:

**Comment by jorisvandenbossche** [comment]
Yes, I was testing on Windows 7.

For python 3, as you can see `fiona` is fetched from defaults (using py3.4):
```
C:\Users\vdbosscj>conda create -n geopandas_test3 -c ioos geopandas python=3
Fetching package metadata: ......
Solving package specifications: ................................................
......
Package plan for installation in environment C:\Anaconda\envs\geopandas_test3:

The following NEW packages will be INSTALLED:

    click:           4.1-py34_0        defaults
    cligj:           0.1.0-py34_0      defaults
    descartes:       1.0.1-py34_0      ioos
    fiona:           1.5.1-np19py34_0  defaults
    gdal:            1.11.2-np19py34_1 defaults
    geopandas:       0.1.1-py34_1      ioos
    geopy:           1.10.0-py34_0     ioos
    geos:            3.4.2-vc10_0      defaults [vc10]
    libspatialindex: 1.8.5-1           ioos
    matplotlib:      1.4.3-np19py34_1  defaults
    numpy:           1.9.3-py34_0      defaults
    pandas:          0.17.0-np19py34_0 defaults
    pip:             7.1.2-py34_0      defaults
    pyparsing:       2.0.3-py34_0      defaults
    pyproj:          1.9.4-py34_3      ioos
    pyqt:            4.10.4-py34_1     defaults
    python:          3.4.3-0           defaults
    python-dateutil: 2.4.2-py34_0      defaults
    pytz:            2015.7-py34_0     defaults
    rtree:           0.8.2-py34_2      ioos
    setuptools:      18.5-py34_0       defaults
    shapely:         1.5.12-np19py34_1 ioos
    six:             1.10.0-py34_0     defaults
    sqlalchemy:      1.0.9-py34_0      defaults
    wheel:           0.26.0-py34_1     defaults

Proceed ([y]/n)?
```

And adding `fiona` to the `create` command does not change it

**Comment by ocefpaf** [comment]
Try this instead:

```shell
conda create -n geopandas_test3 -c ioos geopandas python=3.4
```

I could not build `gdal` for Python 3.5 on Windows (not sure why yet), and conda is not smart enough to solve the dependencies by giving a major Python version only (`python=3`).

**Comment by jorisvandenbossche** [comment]
@ocetpaf aha, yes, this is picking the correct versions from the ioos channel! thanks

**Comment by fmaussion** [comment]
@ocefpaf I could try it on Windows and Debian, with python 2.7 and 3.4. Works as expected, thanks a lot! Thanks everybody, nice to see that we all have to deal with similar gis-dependency nightmares. 

A word about whether the latest versions of the packages should be on conda or not: my opinion is that stability is more important than updates. If someone wants to use the very latest packages, he/she has to take care about it and use pip or whatever. Conda is awesome and really smart, but it is obviously impossible to handle all possible dependency trees on every machine. In particular, conda has the tendency to update packages without your consent, which is a problem for reproducible science ("wait, which version of numpy was I using when I wrote this paper last year?").

**Comment by ocefpaf** [comment]
> In particular, conda has the tendency to update packages without your consent, which is a problem for reproducible science ("wait, which version of numpy was I using when I wrote this paper last year?").

This is off topic but worth mentioning:  if you worry about the reproducibility problem it is worth taking a look at [conda-execute](https://github.com/pelson/conda-execute).
