### ISSUE TITLE
Enable windows build via AppVeyor

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#64]
- [X] add `appveyor.yml`
- [ ] start to :sob:

**Comment by ocefpaf** [comment]
@rsignell-usgs [appveyor](http://www.appveyor.com/) does not open its log files like travis-ci.  Should we use my account or should we create an IOOS account and share the password with https://github.com/ioos/conda-recipes contributors?

**Comment by rsignell-usgs** [comment]
I like the ioos account idea.   Can't see much risk of shared account here!  ;-)

**Comment by ocefpaf** [comment]
OK.  Since you are one of the IOOS GitHub admin can you do this and then you share the password with me?

**Comment by rsignell-usgs** [comment]
@ocefpaf , hmmm, looking into this, we need either an e-mail or a github developer account to create an appveyor account, but we have only an IOOS github organization, not an IOOS github developer account.   And I'm not sure we should create one either.   

We could still create a new appveyor account without associating with github, but then we have to still use some e-mail address to sign up.    We could create an IOOS gmail account or something, but perhaps we should just back off and use your (or my) appveyor account for now.   Unless I'm missing something.   I wonder what @pelson and the scitools gang did for an appveyor account.

**Comment by ocefpaf** [comment]
OK.  To move this forward I will use my account.  But in the long run I believe that someone affiliated to IOOS should take over.

**Comment by rsignell-usgs** [comment]
The windows builds certainly are going to be challenging.   Do you think we should pursue the MinGW approach or try to get stuff going with the CMAKE w/ Native Windows Compiler approach?   I wonder how Golhke builds his [windows binaries for python packages](http://www.lfd.uci.edu/~gohlke/pythonlibs/).  

On a related note, I'm not sure a Native Windows Fortran compiler is available on Appveyor, but of course we would use gfortran with MinGW.

**Comment by rsignell-usgs** [comment]
Some interesting links here?
https://github.com/JuliaLang/julia/blob/master/appveyor.yml
https://github.com/JuliaLang/julia/blob/master/README.windows.md

**Comment by ocefpaf** [comment]
> Do you think we should pursue the MinGW approach or try to get stuff going with the CMAKE w/ Native Windows Compiler approach?

No idea.  My experience here is zero.  My guess is that CMAKE is more "AppVeyor friendly."

> I wonder how Golhke builds his windows binaries for python packages?

You are not alone there...

> On a related note, I'm not sure a Native Windows Fortran compiler is available on Appveyor, but of course we could use gfortran with MinGW.

I have to read AppVeyor docs, but I believe you are correct.

PS: Thanks for the Julian links.  Reading them now.

**Comment by ocefpaf** [comment]
Closing this issue and opening new PR/issue for each build wall we hit.

PS: Several packages are already available for win32 and win64:

https://binstar.org/organization/IOOS/dashboard/channels/main
