### ISSUE TITLE
IOOS env has wrong version of cf_units

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/conda-recipes#649]
I just tried installing a new copy of miniconda on windows and tried creating the IOOS environment.  I got back:
```
Warning: 4 possible package resolutions (only showing differing packages):
        [u'cf_units-0.1.1-py27_0.tar.bz2', u'compliance-checker-2.0.0-py27_2.tar
.bz2', u'snuggs-1.3.1-py27_0.tar.bz2'],
        [u'cf_units-1.0.0-py27_0.tar.bz2', u'compliance-checker-2.0.0-py27_1.tar
.bz2', u'snuggs-1.3.1-py27_0.tar.bz2'],
        [u'cf_units-1.0.0-py27_0.tar.bz2', u'compliance-checker-2.0.0-py27_1.tar
.bz2', u'snuggs-1.3.1-np110py27_0.tar.bz2'],
        [u'cf_units-0.1.1-py27_0.tar.bz2', u'compliance-checker-2.0.0-py27_2.tar
.bz2', u'snuggs-1.3.1-np110py27_0.tar.bz2'],
```
and then the environment is created with `cf_units=0.1.1`, which is incompatible with `iris=1.9.0`.

How do we fix this?

**Comment by ocefpaf** [comment]
`compliance-checker` was pinning `cf_units` down.  PR #650 should fix this.

**Comment by ocefpaf** [comment]
I just tested re-creating the environment we `cf_units` and I got `1.0.0`.  Let me know if that works for you.

**Comment by rsignell-usgs** [comment]
Yes, I get `cf_units=1.0.0` now.  The only warning left when I create the IOOS environment is:
```
Warning: 2 possible package resolutions (only showing differing packages):
        [u'snuggs-1.3.1-py27_0.tar.bz2'],
        [u'snuggs-1.3.1-np110py27_0.tar.bz2'],
```
Can we get rid of that one also?

**Comment by ocefpaf** [comment]
That is a harmless warning, but I can do something about it.  Hold on...

**Comment by ocefpaf** [comment]
The main reason I kept out package is because for some unknown reason the default channel no longer package `snuggs` for Windows (see http://anaconda.org/anaconda/snuggs/files?page=2).  I will check why and sort this out.
