### ISSUE TITLE
Add IOOS logo to the binstar channel

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#67]
[Binstar](https://binstar.org/IOOS) gets the logo automatically from [gravatar](https://signup.wordpress.com/signup/?ref=oauth2&oauth2_redirect=e3e7cde6b34f811c685fba330fea9307%40https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D663e137c52b5de26d47b986e7bf01a18e4060a862f348ee702a13a6d851707b2%26redirect_uri%3Dhttps%253A%252F%252Fen.gravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login&wpcom_connect=1).

We just need to create a free account and add the logo there.

![ioos](https://cloud.githubusercontent.com/assets/950575/6227996/2bffe2a2-b685-11e4-97ab-7a3c2391af1f.png)

**Comment by rsignell-usgs** [comment]
Should I do this one, or are you doing it?

**Comment by ocefpaf** [comment]
I think it is best if you do it.  The gravatar account will not be used for anything but the logo.  Still, I think it should be owned by someone close to IOOS.

**Comment by rsignell-usgs** [comment]
@dpsnowden or @robragsdale, I think it better if one of you do this.   Thanks!

**Comment by rsignell-usgs** [comment]
BTW, it looks like "ioos" is already taken, but looks like "usioos" is available?

**Comment by dpsnowden** [comment]
I'll look at this today. 

Cheers,
Derrick

Sent from my phone. Please excuse my brevity. 




On Tue, Feb 17, 2015 at 6:19 AM -0800, "Rich Signell" <notifications@github.com> wrote:












BTW, it looks like "ioos" is already taken, but looks like "usioos" is available?

**Comment by ocefpaf** [comment]
Done: https://binstar.org/ioos

**Comment by rsignell-usgs** [comment]
What is with all the `<undefined>` at:
https://binstar.org/ioos/_list-packages
It's not just us, eveybody has this issue:
https://binstar.org/anaconda/_list-packages

**Comment by ocefpaf** [comment]
I tried to fill every metadata/form I found and none seems to solve that.  I guess it is a bug in the site.
