### ISSUE TITLE
pyoos packaging questions

### ISSUE THREAD

**Issue by emiliom** [ioos/conda-recipes#685]
In https://github.com/ioos/conda-recipes/blob/master/pyoos/meta.yaml, why is the source/git_url pointing to the ocefpaf fork rather than the source at https://github.com/ioos/pyoos.git?
```yaml
source:
    git_url: https://github.com/ocefpaf/pyoos.git
```
Seems like this could lead to some confusion.

Also, does this mean that the pyoos conda package is built from git, rather than pypi (sorry for my ignorance on conda packaging)? The pypi version (0.6.2, 2014 Aug) is pretty old, but it looks like that's what's built in the ioos channel.

And on a smaller note:
```yaml
about:
    home: https://github.com/asascience-open/pyoos
```
should be updated to https://github.com/ioos/pyoos

**Comment by ocefpaf** [comment]
> In https://github.com/ioos/conda-recipes/blob/master/pyoos/meta.yaml, why is the source/git_url pointing to the ocefpaf fork rather than the source at https://github.com/ioos/pyoos.git?

I guess I wanted to test packaging and forgot this there.  This branch has no new code for pyoos itself, only testing stuff.

I will change that as soon as we have a new release of `pyoos`.

> https://github.com/asascience-open/pyoos should be updated to https://github.com/ioos/pyoos

Done!  It will be in the next pyoos package PR.

(I will leave this issue open until we have a new release and I push these changes.)

**Comment by kwilcox** [comment]
This boils down to `pyoos` needing a maintainer!  I haven't used/looked at it in two years... but still recognize the need for such a library in python.

**Comment by emiliom** [comment]
@ocefpaf, thanks for the update; your plan for next steps seem sensible.

@kwilcox: wow, two years!? Yeah, agreed, a maintainer is needed. I suspect we won't have an ideal, single maintainer (ie, someone who both uses it and knows it inside out) for some time. It's worth bringing it up with Derrick and other pyoos users in the near term. Maybe a topic for one of the "monthly" DMAC calls ...

**Comment by emiliom** [comment]
@ocefpaf, just so I'm not confused: the current pyoos conda package was built with the pyoos release on pypi, right? Even though that's not what's shown on https://github.com/ioos/conda-recipes/blob/master/pyoos/meta.yaml, which suggests that it was built from your github test fork.

Your plan is to create a new pyoos conda package once there's a new pyoos release (and you've handled the [stuff in your pull request](https://github.com/ioos/conda-recipes/pull/687); and you'll create the package from the github master repo, or from pypi?

Thanks.

**Comment by ocefpaf** [comment]
> @ocefpaf, just so I'm not confused: the current pyoos conda package was built with the pyoos release on pypi, right? Even though that's not what's shown on https://github.com/ioos/conda-recipes/blob/master/pyoos/meta.yaml, which suggests that it was built from your github test fork.

The current package was built from that "github test fork," but that branch ony changed the `.travis.yml` file, so it is virtually identical to the PyPI package.  (I thought I was going to change more at the time.)

> Your plan is to create a new pyoos conda package once there's a new pyoos release (and you've handled the [stuff in your pull request](https://github.com/ioos/conda-recipes/pull/687); and you'll create the package from the github master repo, or from pypi?

I can make the package the GitHub or the PyPI release, but not from master or any other branch .  (It will depend on who is the PyPI maintainer and if s/he will upload a source dist there.)

**Comment by emiliom** [comment]
> I can make the package the GitHub or the PyPI release, but not from master or any other branch . (It will depend on who is the PyPI maintainer and if s/he will upload a source dist there.)

I understand now. Sorry, I'm a newbie at this. Thanks.
