### ISSUE TITLE
What should be in the IOOS binstar channel?

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#69]
The current AppVeyor failure on fiona made me raise this question.  To keep the IOOS channel update-to-date we need to lower the burden on the maintainers.  I believe that only the packages who

- are not in the default conda/anaconda distribution and/or
- need a special patch/version/branch to build for our needs

should be on the channel.

The fiona example:  the default channel provides version `1.1.6` and we have an outdated `1.1.2` in the IOOS repository.  Also, the default channel provides all archs and OSes, while our windows build is currently failing.

My vote is to remove fiona, and all the packages that fall into that scenario, from the IOOS channel.  What do you thinnk @rsignell-usgs?

**Comment by ocefpaf** [comment]
BTW:  I tried copy anaconda's recipe for fiona.  But the recipe is not in the [GitHub repository](https://github.com/conda/conda-recipes), and the recipe directory is empty in the binary... :disappointed:

**Comment by rsignell-usgs** [comment]
@ocefpaf, well, I guess this is tricky.    The reason these recipes are here is because at one point either nobody was building them or because we needed more recent versions than we could get elsewhere.  But as more providers come along, I guess we can drop them.   Maybe we could store our old recipes in a deprecated folder or something.

**Comment by ocefpaf** [comment]
I like the deprecation approach.

I will remove `fiona` in my next PR, just to see what is the next package to break.  I am relying on AppVeyor to tell me my next move.  (I thought I'd never say this but I need a windows machine!)

PS: In theory we do not need an actual deprecation folder.  We could just keep the history clean by removing one package at a time and, if there is the need to get it back, we just roll the repository back to that revision using git.  However, I do think that the folder approach is better:  the folder will serve to remember what packages were removed.  Also, it will be easier to re-add a the package in case there is no GitHub expert around.

**Comment by rsignell-usgs** [comment]
@ocefpaf, seems a bit extreme, but you could install a windows virtual machine using virtualbox or the like, couldn't you?

**Comment by ocefpaf** [comment]
> you could install a windows virtual machine using virtualbox or the like, couldn't you

That's the idea. Right now I have an old 32-bit WindowsXP as my VM.  But I need something newer and, even for a  VM, I need a windows license :unamused:

**Comment by ocefpaf** [comment]
I will close this issue and open a PR/issue discussion for each new package we send to the deprecation folder.

**Comment by rsignell-usgs** [comment]
Although we may want to revisit this issue.   I put a lot of stuff *I* needed in this channel that may not be appropriate for general IOOS folks.   Right now this channel is more like everything you and I have wanted to use in the last year or so.   That may be the best stuff for an IOOS environment, but it may not.  I can bring this up at the DMAC meeting in May.
