### ISSUE TITLE
Package request

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#690]
@efiring we have a few requests to provide conda binaries for [CODAS](http://currents.soest.hawaii.edu/docs/adcp_doc/index.html).

I would like to know your opinion before I try anything. (It has been a while since the last time I had to install the whole CODAS and UHDAS stack.)

**Comment by efiring** [comment]
Interesting.  The idea has been in the back of my mind for a while, but I haven't tried anything or thought about it in detail.  Installing into an existing conda environment is easy, at least on linux and OS X.  It has also been done on Windows 7 and maybe 8, but not 10, as far as I know.  I don't know whether the present conda mingw toolchain works on 10.
In any case, if you want to try it, versions of installation instructions are in http://currents.soest.hawaii.edu/docs/adcp_doc/codas_setup/index.html and http://currents.soest.hawaii.edu/ocn_data_analysis/.  In addition to questions about what can be done in various Windows versions there is the wrinkle that our GUI tools for SADCP processing use wxpython, which is not yet available for Python 3.  Apart from that, everything we have should run on 2.7 or 3.4+.

**Comment by ocefpaf** [comment]
Thanks @efiring!  I see that the installation is much easier than before.  I will take a shot at it and keep you posted.

**Comment by ocefpaf** [comment]
Closing this as `codas` and `pycurrents` are in the repo.
