### ISSUE TITLE
Candidates for deprecation

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#72]
@rsignell-usgs let me know which ones I can send to the deprecation folder.

| Package       | Justification                                                                                                         |
|:--------------|:----------------------------------------------------------------------------------------------------------------------|
| enum34        | Newer version in the default channel                                                                                  |
| gensim        | Newer version in the default channel                                                                                  |
| prettyplotlib | The package is [unsupported](https://github.com/olgabot/prettyplotlib) (use seaborn/mpl styles)                       |
| pymc          | Newer version in the default channel [with mkl]                                                                       |
| pytest-cov    | Packages* that have cov as a dependency should make it a test dependency                                              |
| shapely       | Newer version in the default channel                                                                                  |
| starcluster   | Our version is newer than the default channel, do we need the newer?                                                  |
| workerpool    | Newer version in the default channel                                                                                  |

\* pytools and udunitspy

**Comment by rsignell-usgs** [comment]
I agree that all these can be deprecated for now

**Comment by ocefpaf** [comment]
Done in #79, except for `pytest-cov`.  In order to eliminate `pytest-cov` we must change how we build `pytools` and `udunitspy` first.
