### ISSUE TITLE
Setting up IOOS environment according to the wiki instructions fail

### ISSUE THREAD

**Issue by Marston** [ioos/conda-recipes#725]
Hi,

I'm trying to setup the IOOS environment but the instructions on the wiki page fails on my mac El Capitan

url=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
curl $url -o miniconda.sh
bash miniconda.sh -b
export PATH=$HOME/miniconda/bin:$PATH
conda update --yes --all

bash miniconda.sh -b
PREFIX=/Users/marston/miniconda2
miniconda.sh: line 242: md5sum: command not found
WARNING: md5sum mismatch of tar archive
expected: ed903a18296d5cac3844dc26fb31ea98
     got: 
installing: _cache-0.0-py27_x0 ...
installing: python-2.7.11-0 ...
installing: conda-env-2.4.5-py27_0 ...
installing: openssl-1.0.2d-0 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.9.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.19.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
installing: pip-7.1.2-py27_0 ...
installing: wheel-0.26.0-py27_1 ...
installing: setuptools-18.8.1-py27_0 ...
miniconda.sh: line 295: /Users/marston/miniconda2/pkgs/python-2.7.11-0/bin/python: cannot execute binary file
ERROR:
cannot execute native linux-64 binary, output from 'uname -a' is:
Darwin Marstons-MBP.lan 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
Marstons-MBP:~ marston$ 

Can I get some help with this?
/M

**Comment by ocefpaf** [comment]
Looks like you got a broken binary during the download.  Try downloading miniconda manually from.

http://conda.pydata.org/miniconda.html

If that does not work I suggest you contact continuum.  Something might be broken on their side.
