### ISSUE TITLE
Change serial ESMF/ESMPy OSX builds to parallel

### ISSUE THREAD

**Issue by bekozi** [ioos/conda-recipes#737]
The default channel MPI library for OSX has some build issues: https://github.com/ContinuumIO/anaconda-issues/issues/549. Once this is resolved, change OSX builds for ESMF/ESMPy to parallel.

**Comment by ocefpaf** [comment]
Ping @pelson.  (We merged #605 without mpi for now.)

**Comment by ocefpaf** [comment]
Moving this issue to the conda-forge feedstock.

xref: https://github.com/conda-forge/esmf-feedstock/issues/4
