### ISSUE TITLE
Fix the following packages for windows

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#74]
| Package            | Issue                                                                                                                |
|:-------------------|:---------------------------------------------------------------------------------------------------------------------|
| ~~mysql-python~~   | Cannot open include file: 'config-win.h': No such file or directory                                                  |
| rasterio           | Cannot open include file: 'cpl_conv.h': No such file or directory                                                    |
| ~~pymc~~           | Requires a Fortran compiler                                                                                          |
| octant             | Requires a Fortran compiler                                                                                          |
| rtree              | Requires libspatialindex                                                                                             |
| ~~udunitspy~~      | Requires swig                                                                                                        |
| ~~pytools~~        | Requires udunitspy  (If that is not essential consider making it a soft dependency)                                  |
| compliance-checker | Requires udunitspy                                                                                                   |
| ~~pycsw~~          | ~~Requires psycopg2 (that requires postgresql) [pip workaround works for win64]~~                                    |
| ~~tappy~~          | ~~MD5 check is failing.  Probable [sourceforge](http://downloads.sourceforge.net/tappy/tappy-0.9.0.tar.gz) failure~~ |
| ~~sci-wms~~        | ~~Does not build anything. (Cherry pick the commit deccd4e)~~ PR #73                                                 |
| ~~rdflib~~         | ~~Requires to get sparqlwrapper to circumvent the circular dependency  (Cherry pick the commit ded3611)~~            |
| ~~sparqlwrapper~~  | ~~Requires rdflib  (Cherry pick the commit ded3611)~~                                                                |

**Comment by ocefpaf** [comment]
I already addressed the low hanging fruit on PRs #73, #75.  I will try `pymc` and `octant` soon.

Notes from @rsignell-usgs:
> @aashish24 pointed me toward a CMAKE-driven GDAL here: https://github.com/nextgis/gdal_svn/tree/cmake4gdal

`GDAL` is needed that for `rasterio`.

**Comment by rsignell-usgs** [comment]
for `pycsw` there are lots of `psycopg2` packages for conda: https://binstar.org/search?q=psycopg2

**Comment by ocefpaf** [comment]
Yes, I looked them all.  Ours, btw, is a copy of this one (the only worked):

https://binstar.org/rm/psycopg2/files

This one is is promising, but it is missing a dependency (postgresql):

https://binstar.org/timka/psycopg2

The rest of the packages for windows are either based on this fork "ssh://hg@bitbucket.org/topper/psycopg2-win32-py27 # [win32 and py27]" or they are copies without a recipe.

**Comment by ocefpaf** [comment]
@rsignell-usgs if win32 is crucial I can create a mix with "ssh://hg@bitbucket.org/topper/psycopg2-win32-py27" and the current setup.  But I'd rather not...

**Comment by rsignell-usgs** [comment]
Wow, what a mess.   I should have known you wouldn't have missed something simple!
No, win32 is not crucial for pycsw, IMHO.

**Comment by ocefpaf** [comment]
If you want to look how I spend my day (and how all those packages appeared up on binstar) look at this mess: https://github.com/ioos/conda-recipes/pull/71

For a moment I thought that AppVeyor would kick me out.

**Comment by ocefpaf** [comment]
@rsignell-usgs I have a few questions for you:

1) To allow build/upload for Travis and AppVeyor at merge time we need to
remove all failures.  Are you OK if we disable (temporally) the following
Windows builds?

- pymc
- rtree
- octant
- pytools
- rasterio
- udunitspy
- mysql-python
- compliance-checker

Note that this issue will remain open until we find a way to build them on
Windows!

2) Travis is working fine and every successful merge trigger build/upload, but
AppVeyor is not!  I tricked AppVeyor by using my fork instead of the
ioos/conda-recipes official repository.  To fix that we need someone with IOOS
GitHub admin rights to enable the PR hook (see #70).


3) To get new builds when just updating a recipe (not the software version)
we **must** increment the build number.  The question is: do you want this
information to be in the README file or in a wiki?
(See https://github.com/SciTools/conda-recipes-scitools/blob/master/README.md)

**Comment by rsignell-usgs** [comment]
1) yes, fine.
2) I can enable the PR hook, but I don't know exactly how to do it.  Perhaps we can walk through it tomorrow. 
3) let's move everything to the wiki and just put "see the wiki" in the Readme.md

**Comment by ocefpaf** [comment]
Not to self: I do not think it is worth pursuing `udunitspy` for windows, it is easier to adapt `compliance-checker` to use `cf_units` instead.

**Comment by ocefpaf** [comment]
I opened separate issue for each of the remaining packages.  Closing this.
