### ISSUE TITLE
update ulmo recipe for new release (v0.8.2)

### ISSUE THREAD

**Issue by dharhas** [ioos/conda-recipes#741]
@ocefpaf 

Hey we just did a point release for ulmo with a few bugfixes and an additional data source. Can you update the conda package on the ioos channel. Thanks.

**Comment by ocefpaf** [comment]
Done in #742 

@dharhas we are limiting `pytables` to `<=3.1.1` on Windows and Python 3, but that version is not available for Python 3.5.  Is that condition still true? (I don't remember why we need that version.)

**Comment by dharhas** [comment]
@ocefpaf pytables 3.2.0 had a hard crash on python 3.4/windows which is why we had the limit. They may have fixed it by now.
