### ISSUE TITLE
Remaining incompatibilities for ESMPy on RHEL6

### ISSUE THREAD

**Issue by pp-mo** [ioos/conda-recipes#773]
I'm currently trying to regularise our support for regridding with ESMF in [Iris](https://github.com/SciTools/iris).
Unfortunately, I finding there are still problems installing this here (UK Met Office), which are presumably related to the rather outdated state of our current software stack, even though it is based on RHEL6.

Maybe all it needs is to be built against an older stack?
I would be great to get this working

**Comment by pp-mo** [comment]
Hi @ocefpaf 
I hope you will be interested in making the link with Iris.
If I  can get an installation here, I can fix Iris code, and with a suitable conda channel we can upgrade our ESMPy routines and enable testing under Travis, which will stop the code going stale again !

Status: I am currently unable to make a working installation.
I did previously get it working up to release 6.2.0.
I have more recently been communicating with Ryan OKuinghttons to resolve the problems, but I've got a bit stuck.
So I was rather hoping that your builds would be a magic solution !!

I've tested with the suggested ```conda install -c https://conda.anaconda.org/ioos esmpy```, on a bare python2.7 environment.
My latest result is :
```
(ioos_esmpy)[itpp@eldxxx bgd]$ python -c "import ESMF"
Traceback (most recent call last):
  File "/home/h05/itpp/miniconda/envs/ioos_esmpy/lib/python2.7/site-packages/ESMF/interface/loadESMF.py", line 122, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/home/h05/itpp/miniconda/envs/ioos_esmpy/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcom_err.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/h05/itpp/miniconda/envs/ioos_esmpy/lib/python2.7/site-packages/ESMF/__init__.py", line 56, in <module>
    from api.esmpymanager import *
  File "/home/h05/itpp/miniconda/envs/ioos_esmpy/lib/python2.7/site-packages/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/home/h05/itpp/miniconda/envs/ioos_esmpy/lib/python2.7/site-packages/ESMF/interface/cbindings.py", line 12, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/home/h05/itpp/miniconda/envs/ioos_esmpy/lib/python2.7/site-packages/ESMF/interface/loadESMF.py", line 125, in <module>
    raise ImportError('The ESMF shared library did not load properly.')
ImportError: The ESMF shared library did not load properly.
(ioos_esmpy)[itpp@eldxxx bgd]$ 
```

If I poke around, I find that we currently  have ```libcom_err.so.2.1```, but no ".3" versions.

For reference, with Ryan's help, I got as far as some similar problems with not having ```libgfortran.so.3```.

**Comment by pp-mo** [comment]
P.S. I can't seem to add labels to this.
Is that intentional ?

**Comment by ocefpaf** [comment]
> P.S. I can't seem to add labels to this.
> Is that intentional ?

Patrick,

We are interested, but I am in a conference now. I will get back to you
next week.

**Comment by pp-mo** [comment]
> We are interested, but I am in a conference now. I will get back to you next week.

No great rush here.
Thanks !

**Comment by bekozi** [comment]
You should be able to fix this by running: ``conda install krb5``. This has popped up across a number of packages. I'm not sure where the ``libcom`` link is coming from as ``krb5`` is not an ``esmpy`` dependency. See https://github.com/ioos/conda-recipes/issues/771.

Ping @rokuingh.

**Comment by pp-mo** [comment]
> @bekozi  You should be able to fix this by running: ```conda install krb5```

Thanks, I have tried that and it does help.
I think I am still having other problems, though.
Not quite sorted yet, I will post again when I have sorted out where I am now at ...

**Comment by pp-mo** [comment]
I've moved this effort here, as suggested : https://github.com/conda-forge/staged-recipes/pull/130
