### ISSUE TITLE
rasterio dll load failed

### ISSUE THREAD

**Issue by jdmcbr** [ioos/conda-recipes#775]
Thanks for all the conda recipes for geospatial packages. They've been a big help in easily getting up and running on Windows. I have a fairly minor issue, hopefully one with a simple fix.

I have a fresh Anaconda3 install (2.3.0), with python 3.4.3, in Windows 8.0 (64 bit). I use `conda install -c https://conda.anaconda.org/anaconda rasterio`. Then, if I try to import rasterio without first importing gdal, I get the following:

```
>>> import rasterio
Traceback (most recent call last):
 
   File "<ipython-input-1-34708b297916>", line 1, in <module>
     import rasterio
 
   File "C:\Anaconda3\lib\site-packages\rasterio\__init__.py", line 8, in <module>
    from rasterio._base import eval_window, window_shape, window_index
 
ImportError: DLL load failed: The specified module could not be found.
```

It appears that simply importing gdal before rasterio solves this problem. While that obviously works, if there is a simple fix that would let `import rasterio` work straightaway, that would be great.

**Comment by ocefpaf** [comment]
> It appears that simply importing gdal before rasterio solves this problem.

I will take a look, but that sounds really weird.  Do you have any other gdal install by any chance? Can you send me the results of the following commands:

```shell
conda list gdal
conda list rasterio
python -c 'import rasterio; print(rasterio.__version__)'
```

**Comment by jdmcbr** [comment]
I don't believe I have any other `gdal` install on my computer. 

```
C:\Anaconda3>conda list gdal
# packages in environment at C:\Anaconda3:
#
gdal                      1.11.3              np110py34_1    ioos

C:\Anaconda3>conda list rasterio
# packages in environment at C:\Anaconda3:
#
rasterio                  0.31.0              np110py34_0    ioos

C:\Anaconda3>python -c "import rasterio; print(rasterio.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\rasterio\__init__.py", line 8, in <module>
    from rasterio._base import eval_window, window_shape, window_index
ImportError: DLL load failed: The specified module could not be found.

C:\Anaconda3>python -c "import gdal; import rasterio; print(rasterio.__version__)"
0.31.0
```

**Comment by ocefpaf** [comment]
I just tested this,

```shell
conda create -n TEST python=3.4 rasterio
activate TEST
python -c "import rasterio; print(rasterio.__version__)"
```

on a Windows XP 32-bit with machine with miniconda and it works.  I don't own a Win64 to make further tests.  Since the tests also pass on our Win64 CI at (`AppVeyor`) I cannot do much more for you.  Can you try the exact lines above in your setup and let me know what happens?

**Comment by jdmcbr** [comment]
That seems to get the anaconda `rasterio`, version 0.25.0. Which is what I am currently using, and works.

**Comment by ocefpaf** [comment]
That is weird, if you have the ioos channel added that should get you rasterio 0.31 and not 0.25. But if that works...

PS: What is the output of  `conda info`?

**Comment by jdmcbr** [comment]
Oops, I just copied your command, without adding the `-c https://conda.anaconda.org/ioos` to it. Adding that to the above, I'm able to get 0.31.0 to install correctly in the `TEST` environment. I guess I must have some remnants of an old install causing problems then?

conda info:
```
C:\Anaconda3>conda info
Current conda install:

             platform : win-64
        conda version : 3.19.3
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by ocefpaf** [comment]
> I guess I must have some remnants of an old install causing problems then?

Probably.  I recommend the use of environments to avoid that kind of trouble. (And to increase the reproducibility of your work :wink:)

**Comment by jdmcbr** [comment]
Okay, thank you for your assistance.
