### ISSUE TITLE
Already in conda-forge and need to be expanded here

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#805]
- [ ] netcdf-fortran
- [ ] esmf
- [ ] esmpy

**Comment by ocefpaf** [comment]
Change of plans. After speaking with @rsignell-usgs we will shutdown this repository and the ioos channel.

**Comment by pelson** [comment]
> Change of plans. After speaking with @rsignell-usgs we will shutdown this repository and the ioos channel.

Wow. That is awesome! Great news!

**Comment by ocefpaf** [comment]
> Wow. That is awesome! Great news!

I am already using conda-forge in production. (I just need to get the rest of the recipes from conda-recipes-scitools into conda-forge :wink:)
