### ISSUE TITLE
Issue with installing windspharm

### ISSUE THREAD

**Issue by DamienIrving** [ioos/conda-recipes#813]
Just to let the IOOS team know, myself and @didiermonselesan have just logged an issue about installing windspharm on Mac OS X El Capitan. The error occurs whether you install from the IOOS or ajdawson channel on anaconda.org. 
https://github.com/ajdawson/windspharm/issues/66

Has anyone else had this issue and perhaps found a solution? (if so, perhaps it's best to post that solution on the issue over at the windspharm repo)

**Comment by ocefpaf** [comment]
@DamienIrving I guess that re-building `pyspharm` with conda's `gcc` might solve that. I won't fix that here are we are shutting down the IOOS channel. But I am submitting these packages (with the fix) to conda-forge soon.
