### ISSUE TITLE
libspatialindex

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#87]
Used by `rtree` (#224).

**Note to self:**

- [ ] http://lists.gispython.org/pipermail/spatialindex/2012-December/000336.html
- [ ] https://github.com/libspatialindex/libspatialindex/blob/master/INSTALL.WIN

**Comment by rsignell-usgs** [comment]
@ocefpaf, because libspatialindex already has CMake config file: https://github.com/libspatialindex/libspatialindex/blob/master/CMakeLists.txt
doesn't this mean that all we need to do is create a `bld.bat` similar to:
https://github.com/SciTools/conda-recipes-scitools/blob/master/geos/bld.bat

**Comment by ocefpaf** [comment]
It is on my ToDo list...

**Comment by ocefpaf** [comment]
Note to self: https://github.com/libspatialindex/libspatialindex/blob/master/INSTALL.WIN

**Comment by ocefpaf** [comment]
Done!  See #452
