### ISSUE TITLE
Consolidate `req.txt` files

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#97]
Once we have OSX packages on binstar and tested we can check if the Linux requirements file works for Mac and renamed it to just `req.txt`

**Comment by ocefpaf** [comment]
A quick check on binstar seems that we are OK to test the requirements file and, if successful, act on this issue.

The instructions are [here](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Anaconda-Python-environment-for-MacOS64).  Any volunteers among Mac users out there?

**Comment by rsignell-usgs** [comment]
We consolidated here: 
https://github.com/ioos/conda-recipes/blob/master/00_env_requirements/ioos/ioos_req.txt

**Comment by ocefpaf** [comment]
Did someone test this?  I am just wondering... after what happened to Win64.
